version: '3.9'
services:
  mongodb:
    image: database:1.0.0
    container_name: ${MONGO_HOST}
    build:
      context: ./src/mongo
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodb-v:/data/db

volumes:
  mongodb-v:
    name: 'mongodb-v'
# docker-compose --env-file .env up -d
