version: '3.9'
services:
  mongodb:
    image: databasemdb:1.0.0
    container_name: mongo
    build:
      dockerfile: Dockerfile.mongo
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodb-v:/data/db

  postgres:
    image: databasepg:1.0.0
    restart: always
    container_name: postgres
    build:
      dockerfile: Dockerfile.postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 6543:5432
    volumes:
      - postgres-v:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: my-redis-stack
    ports:
      - '6379:6379' # Redis port
      - '8001:8001' # Redis Insight port
    volumes:
      - redis-v:/data

volumes:
  mongodb-v:
    name: 'mongodb-v'
  postgres-v:
    name: 'postgres-v'
  redis-v:
    name: 'redis-v'
