version: '3.9'
services:
  mongodb:
    image: database:1.0.0
    container_name: mongo
    build:
      context: ./src/mongo
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodb-v:/data/db

  postgres:
    image: databasepg:1.0.0
    restart: always
    container_name: postgres
    build:
      context: ./src/postgres
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 6543:5432
    volumes:
      - postgres-v:/var/lib/postgresql/data

volumes:
  mongodb-v:
    name: 'mongodb-v'
  postgres-v:
    name: 'postgres-v'
